cc_test(
    name = "rising_fluid",
    srcs = ["rising_fluid.cpp"],
    deps=[
        "//lib:kalman_filter",
        "//external:glog",
        "//external:gtest_main",
    ]
)

cc_test(
    name = "falling_object",
    srcs = ["falling_object.cpp"],
    deps=[
        "//lib:kalman_filter",
        "//external:glog",
        "//external:gtest_main",
    ]
)


cc_test(
    name = "moving_object",
    srcs = ["moving_object.cpp"],
    deps=[
        "//lib:kalman_filter",
        "//external:glog",
        "//external:gtest_main",
    ]
)
