cc_test(
    name = "example_1",
    srcs = ["example_1.cpp"],
    deps=[
        "//lib:kalman_filter",
        "//external:glog",
        "//external:gtest_main",
    ]
)

cc_test(
    name = "example_2",
    srcs = ["example_2.cpp"],
    deps=[
        "//lib:kalman_filter",
        "//external:glog",
        "//external:gtest_main",
    ]
)

cc_test(
    name = "example_3",
    srcs = ["example_3.cpp"],
    deps=[
        "//lib:kalman_filter",
        "//external:glog",
        "//external:gtest_main",
    ]
)

